"""
Django settings for sarkar_sanitary project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^3)n9*z3ih5dicx(-!@v1-#6ve$g+gyoj-a%(b4&+b3uy2m#_z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # 👈 Render-এর লাইভ লিংক সাপোর্ট করার জন্য


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # 👈 জ্যাঙ্গো অ্যাডমিন প্যানেল সুন্দর করার জন্য এটি সবার উপরে রাখা হয়েছে
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 👈 Render-এ স্ট্যাটিক ফাইল ও CSS দেখানোর জন্য
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sarkar_sanitary.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # 👈 সঠিক Backend নাম
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sarkar_sanitary.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Extra static folder
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 👈 Render-এ collectstatic এরর দূর করার জন্য
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==============================================================================
# 🎨 JAZZMIN SETTINGS (অ্যাডমিন প্যানেল প্রিমিয়াম ও সুন্দর করার মেইন থিম কোড)
# ==============================================================================

JAZZMIN_SETTINGS = {
    "site_title": "Sarkar Enterprise Admin",
    "site_header": "Sarkar Enterprise",
    "site_brand": "Sarkar Admin",
    "welcome_sign": "Welcome to Sarkar Enterprise Admin Panel",
    "copyright": "Sarkar Enterprise Ltd",
    "search_model": ["shop.ContactMessage"],
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Website", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth.user": "fas fa-user",
        "shop.ContactMessage": "fas fa-envelope",
        "shop.Product": "fas fa-box",
        "shop.Category": "fas fa-list",
        "shop.Cart": "fas fa-shopping-cart",
        "shop.Order": "fas fa-shipping-fast",
    },
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-danger", 
    "accent": "accent-primary",
    "navbar": "navbar-dark bg-dark", 
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_options": {
        "sidebar_fixed": True,
    },
    "sidebar": "sidebar-dark-danger", 
    "sidebar_nav_flat_style": False,
    "theme": "flatly", 
    "dark_mode_theme": None,
}